### PR TITLE
Fix #2

### LINKED ISSUE #2: hopper_minecart
a whole group of shulker boxes dropped on the ground will be directly sucked in, whether the hopper can be made to only suck in one at a time.

### PR DESCRIPTION
**Pull request by WinExp**
I added a rule "minecartOnlyTransferOneShulker" to control the transfering behavior of the hopper minecarts.
When the rule activated, the hopper minecarts will only transfer one shulker box.

### CODE REVIEW

**Comment by kikugie** [comment]
Picking up the entire stack of items is the standard behaviour of hoppers, as well as stacked shulker boxes prior to 1.20.5. What is the use case of this change?

**Comment by WinExp** [comment]
I know this is expected behavior, but it tends to break structures that rely on hopper minecarts to pick up items, as stacked shulker slows down minecarts dramatically

**Comment by kikugie** [comment]
Makes sense, but the way you implemented it makes regular hoppers unable to pick up full stacks. This in turn breaks contraptions like
- Shulker colour sorting
- Automated stacked shulker storages
- Water stream shulker distribution

I suggest making it clear that the rule affect not only hopper minecarts and adding a rule that removes additional slowdown for them.

**Comment by WinExp** [comment]
I add rule to control the behavior of hoppers and hopper minecarts, but I didn`t     test the mods compatibility

**Comment by kikugie** [comment]
I'll test compatibility with Lithium before merging

**Pull request merged**
